experiment_name: "efficientnet_with_image_augmentation"

seed: 0  # for train / validation split
image_augmentation: True

feature_extractor: "efficientnet"
dropout: 0.5
epochs: 50
early_stopping_patience: 10
