study_name: "hpt_study-0"

seed: 0
image_augmentation: False  # due to https://github.com/keras-team/keras-cv/issues/581, image_augmentation must be 

feature_extractor: "efficientnet"
embedding_dim_grid: [128, 256, 512]
intermediate_linear_units_grid: ["[]", "[256]", "[256, 256]", "[512]", "[512, 256]"]  # must be a list of strings for Optuna compatibility
dropout_grid: [0.4, 0.5, 0.6]

epochs: 10
early_stopping_patience: 3

n_trials: 10
