study_name: "hpt_study-0"

seed: 0
image_augmentation: False  # due to https://github.com/keras-team/keras-cv/issues/581, image_augmentation must be 

feature_extractor: "efficientnet"
embedding_dim_grid: [128, 256, 512, 1024]
intermediate_ff_block_units_grid: ["[]", "[256]", "[256, 256]", "[512]", "[512, 256]", "[512, 512]", "[1024]", "[1024, 512]"]  # must be a list of strings for Optuna compatibility

epochs: 10
early_stopping_patience: 3

n_trials: 10
